### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 378: ordinal not in range(128)

### ISSUE THREAD

**Issue by yuwezyu** [emonti/qualcomm-opensource-tools#1]
When I'm parsing the Qualcomm dump which made by QPST, it took this error:
hwj@ubuntu:~/Desktop/Port_COM10$ python /home/hwj/Desktop/tools/linux-ramdump-parser-v2/ramparse.py --32-bit
 -v /home/hwj/Desktop/Port_COM10/vmlinux
 -g /home/hwj/Desktop/android-ndk-r19c/prebuilt/linux-x86_64/bin/gdb 
-n /home/hwj/Desktop/android-ndk-r19c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm
 -a /home/hwj/Desktop/Port_COM10 
-o /home/hwj/Desktop/Port_COM10 –x
Traceback (most recent call last):
  File "/home/hwj/Desktop/tools/linux-ramdump-parser-v2/ramparse.py", line 189, in <module>
    print_out_str('Arguments: {0}'.format(args))
  File "/home/hwj/Desktop/tools/linux-ramdump-parser-v2/print_out.py", line 37, in print_out_str
    out_file.write((string + '\n').encode('utf-8', 'ignore'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 378: ordinal not in range(128)

**Comment by yuwezyu** [comment]
That's noting at all.
